---
- name: Add SSH keys to authorized keys file
  ansible.builtin.lineinfile:
    path: ~/.ssh/authorized_keys
    line: "{{ item }}"
    create: yes
  loop: "{{ ssh_keys }}"
  diff: True

- name: Run apt update
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ package_list }}"

- name: Mount Proxmox SMB share
  ansible.posix.mount:
    src: //10.100.10.15/proxmox
    path: /mnt/proxmox
    opts: "rw,vers=3,file_mode=0600,dir_mode=0700,dom=domain.local,username={{ smb_username }},password={{ smb_password }}"
    fstype: cifs
    state: mounted
