---

- name: Modify cron timezone
  ansible.builtin.cron:
    name: CRON_TZ
    env: yes
    job: America/Detroit

- name: "Tempalte crontab: daily fortune email"
  ansible.builtin.cron:
    name: "Ansible: daily fortune email"
    minute: "0"
    hour: "6"
    job: "fortune -c -e | cowsay | mail -s \"Moo-sery Loves Company: Today's Inappropriate Fortune\" {{ email_list }}"
  diff: true
