version: '3.3'
services:
    prometheus:
        container_name: prometheus
        ports:
          - '127.0.0.1:9090:9090'
        image: prom/prometheus
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
        restart: "always"
