# ~/docker_compose/cloudflare_ddns/docker-compose.yml
# cloudflare ddns container

version: "3"
services:
  cloudflare-ddns-root:
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - PGID=1000
      - PUID=1000
      - CF_API_TOKEN=<PASTE_API_KEY_HERE>
      - DOMAINS=domain.com
      - PROXIED=true
      - UPDATE_CRON=@every 120m
      - UPDATE_ON_START=true

  cloudflare-ddns-subdomains:
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - PGID=1000
      - PUID=1000
      - CF_API_TOKEN=<PASTE_API_KEY_HERE>
      - DOMAINS=example.domain.com
      - PROXIED=false
      - UPDATE_CRON=@every 120m
      - UPDATE_ON_START=true
