apiVersion: v1
kind: Secret
metadata:
  name: external-dns-cloudflare
  namespace: external-dns
stringData:
  api-token: REPLACE_ME
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "1970-01-01T00:00:00Z"
  mac: "REPLACE_ME"
  pgp: []
  encrypted_regex: "^(data|stringData)$"
  version: "3.8.1"
