apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflared
spec:
    secretTemplates:
        - name: cloudflare-tunnel-token
          stringData:
            token: ENC[AES256_GCM,data:p80sr8ES+od5XO0kCvYOArMUXhu+EXRmF29uSETvLzfHleXNFpLJBUdlk/kESRVy2GmFCW6kSOgEYCLsnGJWOdFpt3BsLNiEl+WO4bA/BzDLziTMjEBQuelMJlBbeW/Xk6W2UREwkJM0EhUDyu+mt4hY+gYD6zhb7vixpV8xr/Zd8+QdzXIGzZ98va1hTyuu4ZqrRZhHC+WqXxUU4EKQSwyDgJcXD0kzfiEkK5vfpy/4VpTgu6i+VA==,iv:TQM3OiGqOE8wYTCpkxIXGUC/dxG7ntJ11kg6tb05br8=,tag:/KJAP4YY3RJ7UKOvGxMlWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYjlJblZ5SnY3Qm9EdVpN
            WjRZM3BJUmRadDJ3emttaHdvOUI5V2RXdlFNCnlldzZKVDFhd3pYbUJoWEVoSGhE
            R0toMnBlLzFQUnJ4YWhIZElOcHZXM2sKLS0tIHQ5L0d0YWs4ZFZNb2s1Mld2Z0Y3
            dGFZaWRMR0tqb3F6SVN2N2lJVFhmblEKm66E4ZDxKYvrzIFKUgBJgC6GEzp8+kga
            WSTp8HDPczCIwfWXDoB5PWomJW0XiUVjzbeZPTGyaFAvGDjX2sl2Ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a4v9rkhc0lmv9ju0yzsp5gmas7hu982q23jrq4y44dhuqgcsua4qe3wl9x
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T05:30:36Z"
    mac: ENC[AES256_GCM,data:35MYjEbYyaAN4DSgnptbgX1yvXGi93QarwLqBwBnDUxDWnJIOm0GjoYu5n+ZPhDMmG1aMeki85tTYqFgI0uZjDT+ULIO0Q4MIjZCOO52GT141hd5pDn+e1IVt5RGaSC0ZOUVx/5ksVvxG3m6RtbiKdfZvC/DXiBDXmhQCcZXTbw=,iv:B5Ez188IEqmQd+Sr/NTI2P/tkOSXXx6Sxdq9ZfNrkDc=,tag:guhfW7IC/zUs9o8INz3UbQ==,type:str]
    version: 3.13.2
