---

- name: Install required base packages
  ansible.builtin.package:
    name:
      - cifs-utils
      - epel-release
      - yum-utils
    state: present

- name: Add Docker CE repo
  ansible.builtin.command: >
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker engine
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Enable and start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create media group
  ansible.builtin.group:
    name: media
    gid: 1002
    state: present

- name: Create media user
  ansible.builtin.user:
    name: media
    comment: media automation user
    uid: 1002
    group: media

- name: Mount media SMB share
  ansible.posix.mount:
    src: //10.100.10.15/Media
    path: /mnt/media
    opts: "rw,vers=3,uid=1002,gid=1002,file_mode=0664,dir_mode=0775,dom=domain.local,username={{ smb_username }},password={{ smb_password }}"
    fstype: cifs
    state: mounted

- name: Create a container directory if it does not exist
  ansible.builtin.file:
    path: "{{ base_dir }}"
    state: directory
    mode: "0755"

- name: Update configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ base_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - docker-compose.yml
  diff: true

- name: Pull container updates with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ base_dir }}"
    pull: always
  notify: Restart container(s)
