---

- name: Package install cifs-utils
  ansible.builtin.package:
    name: cifs-utils
    state: present

- name: Package install epel-release
  ansible.builtin.package:
    name: epel-release
    state: present

- name: Package install podman-compose
  ansible.builtin.package:
    name: podman-compose
    state: present

- name: Create media group
  ansible.builtin.group:
    name: media
    gid: 1002
    state: present

- name: Create media user
  ansible.builtin.user:
    name: media
    comment: media automation user
    uid: 1002
    group: media

- name: Mount media SMB share
  ansible.posix.mount:
    src: //10.100.10.15/Media
    path: /mnt/media
    opts: "rw,vers=3,uid=1002,gid=1002,file_mode=0664,dir_mode=0775,dom=domain.local,username={{ smb_username }},password={{ smb_password }}"
    fstype: cifs
    state: mounted

- name: Create a container directory if it does not exist
  ansible.builtin.file:
    path: "{{ base_dir }}"
    state: directory
    mode: "0755"

- name: Update configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ base_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - docker-compose.yml
  diff: True
# notify: Restart container(s)

- name: Pull container updates
  ansible.builtin.command:
    cmd: podman-compose -f {{ base_dir }}/docker-compose.yml up -d
    chdir: "{{ base_dir }}"
  register: podman_compose_result
  changed_when: >
    'Creating' in podman_compose_result.stdout
    or 'Recreating' in podman_compose_result.stdout
    or 'Pulling' in podman_compose_result.stdout
    or 'Starting' in podman_compose_result.stdout
  failed_when: podman_compose_result.rc != 0
  notify: Restart container(s)
