---

- name: Package install cifs-utils
  ansible.builtin.package:
    name: cifs-utils
    state: present

- name: Create media group
  ansible.builtin.group:
    name: media
    gid: 1002
    state: present

- name: Create media user
  ansible.builtin.user:
    name: media
    comment: media automation user
    uid: 1002
    group: media

- name: Mount media SMB share
  ansible.posix.mount:
    src: //10.100.10.15/Media
    path: /mnt/media
    opts: "rw,vers=3,file_mode=0600,dir_mode=0700,dom=domain.local,username={{ smb_username }},password={{ smb_password }}"
    fstype: cifs
    state: mounted

- name: Create a container directory if it does not exist
  ansible.builtin.file:
    path: "{{ base_dir }}"
    state: directory
    mode: "0755"

- name: Update configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ base_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - docker-compose.yml
  diff: True
# notify: Restart container(s)

- name: Pull container updates
  community.docker.docker_compose_v2:
    project_src: "{{ base_dir }}"
    pull: always
  notify: Restart container(s)
