apiVersion: v1
kind: Secret
metadata:
  name: velero-credentials
  namespace: velero
stringData:
  cloud: |
    [default]
    aws_access_key_id=REPLACE_ME
    aws_secret_access_key=REPLACE_ME
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "1970-01-01T00:00:00Z"
  mac: "REPLACE_ME"
  pgp: []
  encrypted_regex: "^(data|stringData)$"
  version: "3.8.1"
