apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smb-csi-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://REPLACE_ME/cookbooks.git
    targetRevision: main
    path: kubernetes/gitops/apps/smb-csi/config
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
