apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homepage-vars
    namespace: homepage
spec:
    secretTemplates:
        - name: homepage-vars
          stringData:
            HOMEPAGE_VAR_PROXMOX_API_TOKEN_ID: ENC[AES256_GCM,data:b7fTjBkehSoMQ556jAccTwo8yLVDf9RAbQ4=,iv:jdHuzzpXfNAUdNa4eloVlbw/yl74QPFc6AImjupFNJw=,tag:O0A8+IMDQ9Zb2fuD/9TZOQ==,type:str]
            HOMEPAGE_VAR_PROXMOX_API_KEY: ENC[AES256_GCM,data:zdzumme0mGAB2qHITwOq2LrfxBuv9RqFHs4m4S2yrFRteMBZ,iv:rXVLPxTZmknCsIR5eQ+2UmqzSyX0x54t3w2vVpQ3D/s=,tag:xlB3P1/jznFbHY/beW602Q==,type:str]
            HOMEPAGE_VAR_PLEX_KEY: ENC[AES256_GCM,data:DMPiib95tTONNvYBSW1nnAC5CgY=,iv:/8HmiiurJuzkyOdKd1oo0uWaHEc94UOyoURkZ0auru0=,tag:EpOOgCclpGEOAZA8yKB2kA==,type:str]
            HOMEPAGE_VAR_KUMA_DOMAIN: ENC[AES256_GCM,data:vbj6nVWrEOHFfMRYWPnOzvGw6JH/vCXiLnFR,iv:zjyTqx8UDCD2Nir91wZj+Tetu3x5sZ/A2vtrw2V5WAI=,tag:8IJHAvU5kPrLOEmDwTX4IQ==,type:str]
            prowlarr_api_key: ENC[AES256_GCM,data:dUBNzSEr4N3EqJrRp7+89JgBTKzI4y6y3VMl4T7GB4Q=,iv:zuEI6NEp/fUEAskYQihoqoTIFTLZJMTjzqqChdZ3KK8=,tag:vsiaTIDwvh+lN/ec0o+yDw==,type:str]
            jellyseerr_key: ENC[AES256_GCM,data:ukfVMUmG1PCDQP51ZpMQo28ELy61s0lx5r+N2aItMfPCjuflshU2MalhZKHBFrPKUnuI394orI9LiqjRqdyaerKGgC4=,iv:m8mhTPMLccte0YHga23st9zIybYHoJKNHRMj0UkrDwg=,tag:szgjpzVgP0kTiZCPOgkzpg==,type:str]
            radarr_key: ENC[AES256_GCM,data:hQRWvkbY7QojhqX49C9W0X42lL/e/Uwwpxv2iOXSjyg=,iv:EHfd536iMfJfpeWWm2znSS9nxz54TtHYqb9nfR7JODY=,tag:5lvClRm27Ub1HKfAtdTo1w==,type:str]
            sonarr_key: ENC[AES256_GCM,data:qGyWNU8BcQ4Fy7wbSJDmwt9zUFZhZ3BIMLzIsF7M9m8=,iv:wDGqukZSAubElwrexvPIlWwrPX4K1Pwy76SY6R8DpM0=,tag:7ncu6lgzh2+H56vxe3aHag==,type:str]
            sabnzbd_key: ENC[AES256_GCM,data:xAYtj9StH8oztxSVwwiQgNQknlxrIgWYE9+5/Hs9WEI=,iv:6aj8Wr4ZIyU1KLVSZ4f2SoVHNlLriyezFfpoTyRfzM0=,tag:izak3qK0ptE/oLpN/pQEHQ==,type:str]
            truenas_api_key: ENC[AES256_GCM,data:NU2ZgVRMagh8Hnq+k8Qd+hfggYdU3rE8EI2MR80EQhqzZQHV+J2/HHa31AMRW7lR+va/6JniayttYzHUNeJxExdx,iv:YLvnfxTjEIVdibv4MWIFhM1QIo6GhFdCcgqwn9Bxp5A=,tag:om2NW0i67hUHysujcFeIJg==,type:str]
            truenas2_api_key: ENC[AES256_GCM,data:cL1UfuG4orWiIajnYaejtt+HY9e23Fidf3Gxy/Y5Rvv/ZqgtEVwMObTWeTCJOVr36p+RjOi7KSbTYn14UtRw3wso,iv:7hBE/+yopTn9/+tuIyDCNzwEKbOqMNDUsL17rwlZuMg=,tag:K6FxtU5IjbdLE7SpvHtokw==,type:str]
            unifi_controller_username: ENC[AES256_GCM,data:K0B/BLVxXXn8Z7x4sA==,iv:S0iU7E5O8H+62MUF04barh1t+KWSHNQaAlGDGkh5Rgg=,tag:eW9F+dGwosygSL2GmybD8g==,type:str]
            unifi_controller_password: ENC[AES256_GCM,data:afIa662O9paOcpMXJa4U/0UV/ok=,iv:5bR+UgZGU0NpK+6fotDtbRkXPSMrpB5q0sAcNL8DoYg=,tag:ztjwxdiNK2SIHZQxKJGlQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WkcyZTZLZ1M3SC8yTnVx
            TFRVTTN0R3ZDM2V2K3VvS2tDOWNWL1lmVWhrCllUa1lRQU4yaHoyb1FaNm56dng5
            K3hySmdBQUpvV2FmaW54VHRnK3p4dHMKLS0tIGtHdUU3dS9wa01RdVJKeHpyVE1E
            bk1FMFVpQTNPbm9FN0w0cXBQQmkvWlkKThrbJ6dzA3RbWGIMsZXRg7PzNUjPYzxA
            sPX5VA7wMsvN5bi3NMIH2Q4xb11u4QmF9ACrKxu48nMu82vkOHByZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a4v9rkhc0lmv9ju0yzsp5gmas7hu982q23jrq4y44dhuqgcsua4qe3wl9x
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T06:09:33Z"
    mac: ENC[AES256_GCM,data:FOVcNl2wrHLLmu0GyxDrCOJwq4eQrhSTzfx/C3gBwK9yzJ5CVxcy9elwn6sJqaKnIa1PPZTDY9BFeXO3uHgKbfNDYCozq3pDM2Ose52kINqF5nus9qPk+XMGzlxkauZCW4HcyUudnnn49Z9EYpAsX2lxY/EtaEYApw+tYTbVV1c=,iv:su9bsVA0THt+iqfmZdZtuywFYEzlZTCxidGdiVfJ27U=,tag:Imyyrne7iDcrcPwIe6LTNQ==,type:str]
    version: 3.13.2
