#!/bin/bash
# first time setup script for ansible server


echo -e "

  # #     # #         #                                          # #     # #
  # #     # #        # #   ###### ##### ###### #####             # #     # #
####### #######     #   #  #        #   #      #    #          ####### #######
  # #     # #      #     # #####    #   #####  #    #            # #     # #
####### #######    ####### #        #   #      #####           ####### #######
  # #     # #      #     # #        #   #      #   #             # #     # #
  # #     # #      #     # #        #   ###### #    #            # #     # #

  # #     # #      ###                                               # #     # #
  # #     # #       #  #    #  ####  #####   ##   #      #           # #     # #
####### #######     #  ##   # #        #    #  #  #      #         ####### #######
  # #     # #       #  # #  #  ####    #   #    # #      #           # #     # #
####### #######     #  #  # #      #   #   ###### #      #         ####### #######
  # #     # #       #  #   ## #    #   #   #    # #      #           # #     # #
  # #     # #      ### #    #  ####    #   #    # ###### ######      # #     # #

  # #     # #       #####                                       # #     # #
  # #     # #      #     #  ####  #####  # #####  #####         # #     # #
####### #######    #       #    # #    # # #    #   #         ####### #######
  # #     # #       #####  #      #    # # #    #   #           # #     # #
####### #######          # #      #####  # #####    #         ####### #######
  # #     # #      #     # #    # #   #  # #        #           # #     # #
  # #     # #       #####   ####  #    # # #        #           # #     # #

"
####################

echo -e "\n\n"

mkdir -p ~/.ssh

echo "################################################################################"
echo -e "adding Adam's macbook SSH key to this machine"
echo "################################################################################"
echo -e "\n\n"
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICKlWUHi61l2BmJKJTSU/uC+fa2H1a73VdmDxmcwCZRo adam@Fajita-MacBook.lan" >> ~/.ssh/authorized_keys

echo "################################################################################"
echo -e "adding ansible-server's SSH key to this machine"
echo "################################################################################"
echo -e "\n\n"
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAqz7vI3Iur9UmtKiXpH6zNkieG65xjETZuwdUHDTArw root@ansible-server" >> ~/.ssh/authorized_keys

echo "################################################################################"
echo -e "adding Adam's ThinkPad SSH key to this machine"
echo "################################################################################"
echo -e "\n\n"
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICC4J5SgvvxMCSR0aTPldYVbI0FjyZC8mwEbzysaIV07 adam@adam-ThinkPad-P53" >> ~/.ssh/authorized_keys

echo "################################################################################"
echo -e "adding Adam's Laptop-G14 SSH key to this machine"
echo "################################################################################"
echo -e "\n\n"
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICNm9sPo3Q501S4rK/H8lmx2CLGtv9/ZoOReAnvodUmB adam@laptop-g14" >> ~/.ssh/authorized_keys

echo "################################################################################"
echo -e "adding Adam's iPhone SSH key to this machine"
echo "################################################################################"
echo -e "\n\n"
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGqSV52tphcmkvNaq7zzcljKxG5MphLrPrdyLgtAzye9 Generated By Termius" >> ~/.ssh/authorized_keys

echo "################################################################################"
echo -e "adding semaphore's SSH key to this machine"
echo "################################################################################"
echo -e "\n\n"
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBaDNqrKzVKnHd0P9GCLnQKcRDBQv1HsUaB+dxhnZ7rg root@semaphore" >> ~/.ssh/authorized_keys

echo -e "\n\nDone!"