---
base_dir: /opt/homepage
restart_policy: "unless-stopped"

docker_service_extra_dirs:
  - config

docker_service_templates:
  - src: docker-compose.yml.j2
    dest: docker-compose.yml
  - src: services.yaml.j2
    dest: config/services.yaml
  - src: bookmarks.yaml.j2
    dest: config/bookmarks.yaml
  - src: widgets.yaml.j2
    dest: config/widgets.yaml
