apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/spicyFajitas/cookbooks.git
    targetRevision: main
    path: kubernetes/gitops/apps/external-dns/config
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
