---

- name: Check whether k3s is already installed
  ansible.builtin.stat:
    path: "{{ k3s_install_bin }}"
  register: k3s_bin

- name: Install k3s agent
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | \
      K3S_URL="https://{{ hostvars[groups[k3s_server_group][0]].ansible_host }}:{{ k3s_server_port }}" \
      K3S_TOKEN="{{ hostvars[groups[k3s_server_group][0]].k3s_node_token }}" \
      sh -s - agent \
      --node-taint "{{ k3s_node_taint }}" \
      --node-label "{{ k3s_node_label }}"
  when: not k3s_bin.stat.exists
  changed_when: true
