resources:
  - metallb/helm-app.yaml
  - metallb/config-app.yaml
  - longhorn/app.yaml
  - traefik/app.yaml
  - smb-csi/app.yaml
  - smb-csi/config-app.yaml
  - argocd/config-app.yaml
  - external-dns/config-app.yaml
  - external-dns/app.yaml
  - velero/config-app.yaml
  - velero/app.yaml
  - nfs-provisioner/app.yaml
