---
- name: Run apt update
  ansible.builtin.package:
    update_cache: yes

- name: Install required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ package_list }}"

- name: Run apt upgrade
  when: not apt_upgrade_override | default(false)
  ansible.builtin.package:
    upgrade: yes

# - name: Restart services if needed
#   shell: needrestart -r a
