apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
spec:
    secretTemplates:
        - name: cloudflare-api-token
          stringData:
            api-token: ENC[AES256_GCM,data:ywEfqekXj5yacYCSzYQ7fQko1pvSEDXBIL+GM0G6gXDmOm1haxWOXqybwy0dvGoyEGmNbeA=,iv:Zj/Mg3U2/8kGRL3OkVyfY3bG/bNor/E6ID53xiTkD/Y=,tag:WyXuKuzd4s/BdkNdC5/Ycg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOTlvVnIrY1o1cFB4Ylgr
            L1NQWmQ0QmE5WjZIYVUrWjVJMWM3N3JDeUJnCmlZdXJyNmRJSmQrTFRqRkpSTjVL
            ODY5bERCY1dVNklkMmVuQ2FRUjFvZ28KLS0tIGppNUVoeExPOC9pM1VNazZUZXIy
            YzhzWnFGRUJYeXpNV2cwQytldTVtamMKrDhtXTZlzEjLPaylgU1Jmo9r8U45e1SX
            Lw0EBdCVnuDmPQfb7nKBq5vHfYxeXMo+Cj5ASHMEsQs+E0gRQqoJQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a4v9rkhc0lmv9ju0yzsp5gmas7hu982q23jrq4y44dhuqgcsua4qe3wl9x
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T05:30:48Z"
    mac: ENC[AES256_GCM,data:orWaWgNHxM/q+V+KKpEjTKWJOAp+7JCHazK7IU7LP5Q0XpFDm6+Y4Fd7RmF28nmpqXtJyervewOY+67m7F3KyLMxRpM91ozOJnEH+U8Id7byTUVwGpFiTTqXbP2B7j3axcfK47yh0S1uj4tMloB7ZfVJHWfYkV5UgorIrN5luRU=,iv:GuyTy+Z+WNcXDJ5GMNpzkQaSyeIZ6bN9R1izIaIQGwg=,tag:niiYh1KG/Qu3+Ok+o3WwCA==,type:str]
    version: 3.13.2
