---

- name: "Tempalte crontab: git pull"
  ansible.builtin.cron:
    name: "Git pull cookbooks"
    minute: "55"
    hour: "2"
    job: "cd /root/cookbooks; git pull >> /var/log/ansible-runs/git_pull.log 2>&1"

- name: "Template crontab: run semaphore playbook every night on semaphore"
  ansible.builtin.cron:
    name: "common-run on semaphore"
    minute: "0"
    hour: "4" # cannot run this at the same as the semaphore nightly runs
    job: "source /root/venv/bin/activate; cd /root/cookbooks/ansible; ansible-playbook server-semaphore.yml -i inventory/inventory.yml --vault-password-file vault-pass.txt >> /var/log/ansible-runs/server-ansible.log 2>&1"
