apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 7.0.0
    helm:
      values: |
        credentials:
          useSecret: true
          existingSecret: velero-credentials
        configuration:
          provider: aws
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero
              default: true
              config:
                region: us-east-1
                s3ForcePathStyle: "true"
                s3Url: https://truenas.example.com:9000
          volumeSnapshotLocation:
            - name: default
              provider: aws
              config:
                region: us-east-1
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.9.2
            volumeMounts:
              - mountPath: /target
                name: plugins
        deployNodeAgent: true
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
