apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
spec:
    secretTemplates:
        - name: cloudflare-api-token
          stringData:
            api-token: ENC[AES256_GCM,data:ZOvBloRUeHTKedkiYq9BGZrw4GDltyP/T+W+bxgqXKDoPsRloY78SzXJ02akd8l17wjrdPg=,iv:3QdW+1pXIC2Bx/YXf0Eyc44hxLkZGvWeujmCibyCTos=,tag:YywO3Np4nFbvCl04sOx1KA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YUd3RzllbVJ0dW1kQ2Ry
            em41QVBubzlGeTJ5RE9MbytnY21ibCtOU3hzCjRLbGE4eGd3VHhMS3lBVnRGZlBE
            eGtoWU5Jd1pwOG1TSmtJZDlLZkszd3MKLS0tIFNiL1JIZkprN1oyVGlrdTdZVWJJ
            YU1QR1Q1Y1F2dGp3emJxQU9SQUtzZGsK1V6uNRTnaQF0gERlOJF2sgeLTmZxj17I
            Cdyje2yeiextp+X+3P+umxnPbsPCULAPV93N/F6EKGC4SB4iVmkZ5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a4v9rkhc0lmv9ju0yzsp5gmas7hu982q23jrq4y44dhuqgcsua4qe3wl9x
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T05:30:20Z"
    mac: ENC[AES256_GCM,data:QmT/Jstgwfy/v9RmQH8IAhXLkd8cpuOTbjZXNxWru9Aeq6SYcigHbMtWet/Bm5aQ0LTnbekL5UPvLKrmP+31/jnFgMlw6F2LxJ4Lqovo4FcVZR8DYSX9TqfIZnJEHXdbQKV4oY4TvxP73VTF0t0Ah2yp00Nx4dtiFwTlTTEEykY=,iv:YdoJVHoqwYIgV84/2BOu7waS89ccIm9x2M/hFHhKIhg=,tag:faft838ZmFQUa7jsi8ajOQ==,type:str]
    version: 3.13.2
