---
base_dir: /opt/watchtower
container_name: watchtower
host_data_volume: "/opt/{{ container_name }}"
watchtower_image: containrrr/watchtower
watchtower_docker_api_version: "1.44"
watchtower_command: "--cleanup --interval 86,400"
watchtower_volumes:
  - /var/run/docker.sock:/var/run/docker.sock
