---
name: YAML Lint
on: [push]

jobs:
    linting:
        name: "Lint"
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            name: Check out code
          - name: Lint
            uses: ibiqlik/action-yamllint@v3
            with:
                format: parsable
                config_file: .yamllint
                file_or_dir: yml
