name: Markdown Lint

on:
    push:

jobs:
    linting:
        name: "Markdown Linting"
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            name: Check out code
          - name: Lint Code
            uses: docker://avtodev/markdown-lint:v1
            with:
                args: "**/*.md"