---

- name: Apt install cifs-utils
  ansible.builtin.apt:
    name: cifs-utils
    state: present

- name: Create smb credentials file
  ansible.builtin.template:
    src: "smb.j2"
    dest: "/root/.smb"
    mode: "0644"

- name: Create media group
  ansible.builtin.group:
    name: media
    gid: 1002
    state: present

- name: Create media user
  ansible.builtin.user:
    name: media
    comment: media automation user
    uid: 1002
    group: media

- name: Template fstab entries
  ansible.builtin.lineinfile:
    path: "/etc/fstab"
    line: "//10.100.10.15/media    /mnt/media              cifs    credentials=/root/.smb"

- name: Create a container directory if it does not exist
  ansible.builtin.file:
    path: "{{ base_dir }}"
    state: directory
    mode: "0755"

- name: Update configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ base_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - docker-compose.yml
  diff: True
# notify: Restart container(s)

# - name: Ensure services are running
#   community.docker.docker_compose:
#     project_src: "{{ base_dir }}"
#     pull: True
#   notify: Restart container(s)
